{
var speed=6;

var marqueecontents= '<font face="Arial" size="2"><a href="testi_skin.htm?#p1"><b>Grace Sim, Kuching</b></a><br>'
+ 'After using NutriScience Exfo Lift Towel, my skin looks fairer and more radiant. My skin also become firmer and tighter. NutriScience Nanotech Anti-Aging Skincare gives me confidence.</font><br><br>'

+ '<font face="Arial" size="2"><a href="testi_skin.htm?#p2"><b>Siu Ling, Miri</b></a><br>'
+ 'I did a demo on skin peeling and renewal on the back of my left hand only, during the seminar on the 26th June 2005. After 3months, I could still see the difference, with the left hand still lighter in colour and the skin smoother than the right hand, with no side effects. It is amazing!</font><br><br>'

+ '<font face="Arial" size="2"><a href="testi_skin.htm?#p3"><b>Evie Rachmadanita, Indonesian</b></a><br>'
+ 'After only 8 days of using the new skin care products, I am very pleased with the results. I noticed that my complexion is much'  
+ ' fairer with finer texture, the eye bags under my eyes are greatly reduced. </font><br>'

+ '<font face="Arial" size="2"><a href="testi_fat_loss.htm?#p0"><b>Siu Ling from Miri</a></b><br>'
+ 'Good news! Yesterday, Monday 28th Nov, I went and saw 3 people I put on the'
+ '<b> Nanotech Fat Loss and Detox Program NT 200A</b> and they are all doing fantastically well.</font><br><br>'

+ '<font face="Arial" size="2"><a href="testi_fat_loss.htm?#p1"><b>Mdm Wong from Miri</a></b><br>'
+ 'I am 81 years old, with insulin dependent diabetes and high blood pressure.  I went on the <b>PhytoDetox</b> program for a week and a PhytoMeal replacement for 2 weeks.'
+ 'Within 1 week, I had to reduce my insulin injection and my blood pressure also improved.</font><br><br>'

+ '<font face="Arial" size="2"><a href="testi_fat_loss.htm?#p2"><b>Jennifer Ting from Miri</b></a><br>'
+ 'I <b> lost 7kg in 3 weeks, from 70kg to 63kg</b>, while on FusionExcel\'s Nanotech Fat Loss & Detox Program. '
+ 'After the 4-day break, I will continue with the program as I need to lose another 5 or 6kgs. '
+ '<b>Throughout the program, I felt great</b>. When on other diets in the past, I experienced some low back pain and '
+ 'a heavy head, and my family would tell me that I looked drawn and tired.  During this program, I experienced no '
+ 'discomfort and my family and friends told me that I look great.  I normally feel discomfort and some pain during my '
+ 'menstruation but <b> now my menstruation is painless</b>.  I am now fitting into clothes I have not been able to wear '
+ 'for a long time. I feel<b> energetic</b> and I feel <b>very happy</b> with the results of my fat and weight loss. '
+ 'With only one meal replacement a day, I had also found this diet <b> very easy to follow</b>.</font><br><br>'

+ '<font face="Arial" size="2"><a href="testi_fat_loss.htm?#p3"><b>Chong Wen Shyen from Miri</b></a><br>'
+ 'About a month prior to going on FusionExcel’s Nanotech Fat Loss & Detox Program, I had just completed 2 '
+ 'months on another diet program.  During those 2 months, I lost 12kg. After 3 weeks on FusionExcel Fat Loss Program,'
+ '<b> I lost 11kgs, going from 96 to 85kg</b>. My mother told me that during my last diet, she was worried about my '
+ 'health as I looked pale and was also unwell, constantly on the verge of a cold.  However, throughout FusionExcel\'s '
+ 'program, my mother said that I looked<b> refreshed and fit</b>. I feel that my <b>alertness and energy level also '
+ 'improved</b> as the program progressed!  My menstruation was always erratic, being up to 3 months late. '
+ 'While on FusionExcel’s program, my<b> menstruation came exactly when it should and it was also very'
+ 'smooth</b>, not heavy as they often used to be. On top of it all, over the same time period,'
+ '<b> this program cost only HALF of what the other diet cost</b>!  I can\'t wait to continue my program after '
+ 'my 4-day break and will update you on my progress in about 3 weeks\' time!! Thank you, FusionExcel!<br><br></font>'

+ '<font face="Arial" size="2"><a href="testi_fat_loss.htm?#p4"><b>Siu Ling from Miri</b></a><br>'
+ 'As far as I can recall, I was<b> always overweight</b> and had never been able to stick to a diet for more than '
+ '24 hours. I have now completed 21 days on FusionExcel’s Nanotech Fat Loss & Detox Program and'
+ '<b> lost 6kg, from 80kg</b>.  I feel great and did not have to fight the snack attacks too hard. I also started '
+ 'using the FusionExcel SkinCare products at the same time as the diet. My friends and family have commented '
+ 'that I now look<b> fitter and trimmer</b> and my face is <b> brighter and more'
+ 'radiant</b>. I feel great and look forward to starting my diet again tomorrow, after a one-week break.</font><br><br>'

+ '<font face="Arial" size="2"><a href="testi_fat_loss.htm?#p5"><b>Raymond Kueh, Kuching</b></a><br>'
+ 'After taking FusionExcel\'s Nanotech Fat Loss & Detox Program introduction pack for 2 weeks, I lost 4.5kg. '
+ 'It was a wonderful feeling to be able to lose all that unwanted baggage. I’ve tried numerous ways to '
+ 'lose that weight before but mostly in vain. With FusionExcel, it works and I am proof of that.</font><br><br>'

+ '<font face="Arial" size="2"><a href="testi_fat_loss.htm?#p6"><b>Pn Rashidah Leonora, 54, Petaling Jaya</b></a><br>'
+ 'I am on the the 32-day Nanotech Fat Loss & Detox Program, and 6 days into it I noticed improvements in my health. I was' 
+ ' suffering from joint pains around my hip and that has since disappeared. Additionally, I was recently diagnosed' 
+ ' with diabetes and after getting on this program my blood sugar level has reduced significantly. I feel generally'
+ ' better after a few days on this, and as a bonus I\'ve lost a lot of inches around my stomach and the changes are noticeable. </font><br><br>'

+ '<font face="Arial" size="2"><a href="testi_fat_loss.htm?#p8"><b>Wong Lee Fung, 22, Klang</b></a><br>'
+ 'When I started on the Nanotech Fat Loss & Detox Program, my weight was at 54kg with my height at 157cm. I followed'
+ ' the program rather loosely but I still lost 2-3 kgs after 2 weeks. However, what is surprising is that I still lost'
+ ' significant inches and my friends are noticing it. Great program!</font><br><br>'

+ '<font face="Arial" size="2"><a href="testi_fat_loss.htm?#p9"><b>Desmond Ho, Kuala Lumpur</b></a><br>'
+ 'I am not quite 50 years old and have had weight problems since the birth of my 3 children many many moons ago. '
+ 'A few diets over the years had not really worked and the rear got bigger! The tummy too was not far behind.'
+ ' Peaking at 78kg, I am getting poorer by the day, buying clothes to fit my expanding size. Three weeks on FusionExcel\'s '
+ 'Nanotech Fat Loss & Detox Program and 7kg lighter, my children have stopped calling me Daisy Duck. Now, 2 weeks into '
+ 'round 2 of the program, I’m down to 66kg and my children now tell me they would be happy to walk into any club with me. '
+ 'My friends and family are also telling me that I look great!</font><br><br>'

+ '<font face="Arial" size="2"><a href="testi_fat_loss.htm?#p10"><b>Hui Yen, 49, Kuching</b></a><br>'
+ 'Start of Program: 29th Dec 2005 – 80kg'
+ '                  11th Jan 2006 – 75kg'
+ 'Before starting on FusionExcel’s Nanotech Fat Loss & Detox Program, my weight was 80kg, and to my amazement I '
+ 'have lost 5kg in 14 days, and my waist went down by 2 inches. During the whole program I was not a faithful '
+ 'follower of the program diet\'s recommendations that required avoidance of carbohydrates, starchy food and sugar. '
+ 'Certain meals I even took "bak kut teh", chicken chop rice and fried mee! However, I totally cut intake of sugar '
+ 'and other sweetened food and drinks.</font><br><br>'

+ '<font face="Arial" size="2"><a href="testi_skin.htm?#p4"><b>Haslinda Mohd Eunos, Johor Bahru</b></a><br>'
+ 'I was born fair but as I grew up, my teenage years were filled with sports activities, and though I\'ve no acne problem,'
+ ' I have pigmentation due to sun inflammation. I have been using products recommended by beauticians but my pigmentation '
+ 'still remains. Only when I started using NutriScience Nanotech Anti-aging Skincare for 2 weeks that my friends said '
+ 'my pigmentation has lightened down and my skin texture is fairer & lighter. Thanks to FusionExcel, sharing this great '
+ 'product has brought me the opportunity for a facial demo to a Royal VVIP whom is Sultan Iskandar Shah, Sultan of Johor, '
+ 'Malaysia who is very happy with the product. I\'m honored to be part of history as the Royal Highness said that I\'m '
+ 'the first person who has ever touched and cleansed his Highness\'s face & share with him the amazing product. I hope '
+ 'to share more of the goodness of the product range that Fusion Excel will bring into the global market. Thanks to '
+ 'FusionExcel!</font><br><br>'

+ '<font face="Arial" size="2"><a href="testi_skin.htm?#p5"><b>Name: Ariza Fazilla<br>Nationality: KL, Malaysia<br>Age: 27</b></a><br>'
+ 'The first time I saw the NutriScience Nanotech Anti-aging Skincare demonstration, I felt very satisfied with the results. '
+ ' About hearing people talk about the products, I feel like I need to use it because I have a big problem with my '
+ 'blackheads. One day FusionExcel needed a model for their demonstration and I volunteered. After the demo, I could feel '
+ 'the difference. I feel my face is cleaner and smoother. I then made the decision to try the products. After two weeks '
+ 'of using them, I found that my face is smoother, firmer and cleaner than before. And the most unbelievable thing is '
+ 'that my blackheads and eye bags are reduced. Thanks to FusionExcel for their great product! Now, I am proud to see my '
+ 'mom with my new face because all these years she had been complaining about my face. Thanks again to FusionExcel!</font><br><br>'

+ '<font face="Arial" size="2"><a href="testi_skin.htm?#p6"><b>Name : RODZIAH SIDEK<br>Nationality: (Kuala Lumpur) Malaysian<br>Age: 25 years Old</b></a><br>'
+ 'I had been looking for a new skincare product because I have pigmentation on my face. After using NutriScience Nanotech '
+ 'Anti-aging Skincare for only 2 weeks, all my family, my friends and my officemates said my pigmentation has lightened '
+ 'down and my skin texture is fairer & lighter. I’m so excited with the result. Now, I only trust NutriScience Nanotech '
+ 'Anti-aging Skincare. After using this product I feel more confident and my life more meaningful. Thanks to FusionExcel '
+ 'for making my dreams come true!</font><br><br>'

+ '<font face="Arial" size="2"><a href="testi_skin.htm?#p7"><b>Name : Zaifeeda Zainul Abidin<br>Location : KL<br>Age : 27 Years Old</b></a><br>'
+ 'I can feel the difference when FusionExcel performed Skin Care demonstration on my face for the very first time. I can '
+ 'feel the cleanness and my skin felt firmer than before. What makes it more unbelievable is that I could still feel the '
+ 'firmness on my face for the next 2 days after the demonstration. Today, after a month of using NutriScience Nanotech '
+ 'Anti-aging Skincare I feel really satisfied with the result. The blackheads and freckles on my face are now reduced, my '
+ 'skin is fairer than before and there is no more acne. Besides No.1(Desqua Lotion) and No.4(Whitening UV Protector), I '
+ 'feel that No.2( Exfo & Lift Towel) and No.3(Regenerative Cream) are the most remarkable. I will keep on using this '
+ 'NutriScience Nanotech Anti-aging Skincare and will share the information and effectiveness of these products with my '
+ 'family and friends. Nowadays, I wouldn\'t have to worry about the blackheads and acne on my face anymore. I feel that '
+ 'my skin is like during my teenage years. Thanks to Fusion Excel.</font>';

document.write('<marquee scrollAmount="3" WIDTH="172"  HEIGHT="120" BGCOLOR="#ffffff" BEHAVIOR="SCROLL" DIRECTION="UP" HSPACE="5" VSPACE="0" onMouseOver="this.scrollAmount=1;" onMouseOut="this.scrollAmount=3;">'+marqueecontents+'</marquee>');
}